// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: proto/cosmos/lms/v1beta1/quer.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// RegisterAdmin adds a new admin
	RegisterAdmin(ctx context.Context, in *RegisterAdminRequest, opts ...grpc.CallOption) (*RegisterAdminResponse, error)
	// AddStudent adds new student
	AddStudent(ctx context.Context, in *GetstudentsRequest, opts ...grpc.CallOption) (*GetstudentsResponse, error)
	// ApplyLeave request a new leave
	ApplyLeave(ctx context.Context, in *GetLeaveRequestRequest, opts ...grpc.CallOption) (*GetLeaveRequestResponse, error)
	// AcceptLeave accept or reject a leave
	AcceptLeave(ctx context.Context, in *GetLeaveApproveRequest, opts ...grpc.CallOption) (*GetLeaveApproveResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) RegisterAdmin(ctx context.Context, in *RegisterAdminRequest, opts ...grpc.CallOption) (*RegisterAdminResponse, error) {
	out := new(RegisterAdminResponse)
	err := c.cc.Invoke(ctx, "/lms.v1beta1.Query/RegisterAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AddStudent(ctx context.Context, in *GetstudentsRequest, opts ...grpc.CallOption) (*GetstudentsResponse, error) {
	out := new(GetstudentsResponse)
	err := c.cc.Invoke(ctx, "/lms.v1beta1.Query/AddStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ApplyLeave(ctx context.Context, in *GetLeaveRequestRequest, opts ...grpc.CallOption) (*GetLeaveRequestResponse, error) {
	out := new(GetLeaveRequestResponse)
	err := c.cc.Invoke(ctx, "/lms.v1beta1.Query/ApplyLeave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AcceptLeave(ctx context.Context, in *GetLeaveApproveRequest, opts ...grpc.CallOption) (*GetLeaveApproveResponse, error) {
	out := new(GetLeaveApproveResponse)
	err := c.cc.Invoke(ctx, "/lms.v1beta1.Query/AcceptLeave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// RegisterAdmin adds a new admin
	RegisterAdmin(context.Context, *RegisterAdminRequest) (*RegisterAdminResponse, error)
	// AddStudent adds new student
	AddStudent(context.Context, *GetstudentsRequest) (*GetstudentsResponse, error)
	// ApplyLeave request a new leave
	ApplyLeave(context.Context, *GetLeaveRequestRequest) (*GetLeaveRequestResponse, error)
	// AcceptLeave accept or reject a leave
	AcceptLeave(context.Context, *GetLeaveApproveRequest) (*GetLeaveApproveResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) RegisterAdmin(context.Context, *RegisterAdminRequest) (*RegisterAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAdmin not implemented")
}
func (UnimplementedQueryServer) AddStudent(context.Context, *GetstudentsRequest) (*GetstudentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStudent not implemented")
}
func (UnimplementedQueryServer) ApplyLeave(context.Context, *GetLeaveRequestRequest) (*GetLeaveRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyLeave not implemented")
}
func (UnimplementedQueryServer) AcceptLeave(context.Context, *GetLeaveApproveRequest) (*GetLeaveApproveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptLeave not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_RegisterAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegisterAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lms.v1beta1.Query/RegisterAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegisterAdmin(ctx, req.(*RegisterAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AddStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetstudentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AddStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lms.v1beta1.Query/AddStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AddStudent(ctx, req.(*GetstudentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ApplyLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaveRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ApplyLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lms.v1beta1.Query/ApplyLeave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ApplyLeave(ctx, req.(*GetLeaveRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AcceptLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaveApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AcceptLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lms.v1beta1.Query/AcceptLeave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AcceptLeave(ctx, req.(*GetLeaveApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lms.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAdmin",
			Handler:    _Query_RegisterAdmin_Handler,
		},
		{
			MethodName: "AddStudent",
			Handler:    _Query_AddStudent_Handler,
		},
		{
			MethodName: "ApplyLeave",
			Handler:    _Query_ApplyLeave_Handler,
		},
		{
			MethodName: "AcceptLeave",
			Handler:    _Query_AcceptLeave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cosmos/lms/v1beta1/quer.proto",
}
