// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/lms/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetLeaveRequest struct {
}

func (m *GetLeaveRequest) Reset()         { *m = GetLeaveRequest{} }
func (m *GetLeaveRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeaveRequest) ProtoMessage()    {}
func (*GetLeaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{0}
}
func (m *GetLeaveRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveRequest.Merge(m, src)
}
func (m *GetLeaveRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveRequest proto.InternalMessageInfo

// }
// message GetAdminResponse{
//      Admin admin=1;
//      //Address address=2;
// }
type GetstudentsRequest struct {
}

func (m *GetstudentsRequest) Reset()         { *m = GetstudentsRequest{} }
func (m *GetstudentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetstudentsRequest) ProtoMessage()    {}
func (*GetstudentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{1}
}
func (m *GetstudentsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetstudentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetstudentsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetstudentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetstudentsRequest.Merge(m, src)
}
func (m *GetstudentsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetstudentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetstudentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetstudentsRequest proto.InternalMessageInfo

type GetstudentsResponse struct {
	Student []*Student `protobuf:"bytes,1,rep,name=student,proto3" json:"student,omitempty"`
}

func (m *GetstudentsResponse) Reset()         { *m = GetstudentsResponse{} }
func (m *GetstudentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetstudentsResponse) ProtoMessage()    {}
func (*GetstudentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{2}
}
func (m *GetstudentsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetstudentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetstudentsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetstudentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetstudentsResponse.Merge(m, src)
}
func (m *GetstudentsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetstudentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetstudentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetstudentsResponse proto.InternalMessageInfo

func (m *GetstudentsResponse) GetStudent() []*Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type GetstudentRequest struct {
	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *GetstudentRequest) Reset()         { *m = GetstudentRequest{} }
func (m *GetstudentRequest) String() string { return proto.CompactTextString(m) }
func (*GetstudentRequest) ProtoMessage()    {}
func (*GetstudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{3}
}
func (m *GetstudentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetstudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetstudentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetstudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetstudentRequest.Merge(m, src)
}
func (m *GetstudentRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetstudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetstudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetstudentRequest proto.InternalMessageInfo

func (m *GetstudentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetstudentRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetstudentResponse struct {
	Student *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
}

func (m *GetstudentResponse) Reset()         { *m = GetstudentResponse{} }
func (m *GetstudentResponse) String() string { return proto.CompactTextString(m) }
func (*GetstudentResponse) ProtoMessage()    {}
func (*GetstudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{4}
}
func (m *GetstudentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetstudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetstudentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetstudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetstudentResponse.Merge(m, src)
}
func (m *GetstudentResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetstudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetstudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetstudentResponse proto.InternalMessageInfo

func (m *GetstudentResponse) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type GetLeaveReq struct {
}

func (m *GetLeaveReq) Reset()         { *m = GetLeaveReq{} }
func (m *GetLeaveReq) String() string { return proto.CompactTextString(m) }
func (*GetLeaveReq) ProtoMessage()    {}
func (*GetLeaveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{5}
}
func (m *GetLeaveReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveReq.Merge(m, src)
}
func (m *GetLeaveReq) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveReq proto.InternalMessageInfo

type GetLeaveRequestResponse struct {
	Leaverequest []*GetLeaveRequest `protobuf:"bytes,1,rep,name=leaverequest,proto3" json:"leaverequest,omitempty"`
}

func (m *GetLeaveRequestResponse) Reset()         { *m = GetLeaveRequestResponse{} }
func (m *GetLeaveRequestResponse) String() string { return proto.CompactTextString(m) }
func (*GetLeaveRequestResponse) ProtoMessage()    {}
func (*GetLeaveRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{6}
}
func (m *GetLeaveRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveRequestResponse.Merge(m, src)
}
func (m *GetLeaveRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveRequestResponse proto.InternalMessageInfo

func (m *GetLeaveRequestResponse) GetLeaverequest() []*GetLeaveRequest {
	if m != nil {
		return m.Leaverequest
	}
	return nil
}

type GetLeaveApproveRequest struct {
}

func (m *GetLeaveApproveRequest) Reset()         { *m = GetLeaveApproveRequest{} }
func (m *GetLeaveApproveRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeaveApproveRequest) ProtoMessage()    {}
func (*GetLeaveApproveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{7}
}
func (m *GetLeaveApproveRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveApproveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveApproveRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveApproveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveApproveRequest.Merge(m, src)
}
func (m *GetLeaveApproveRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveApproveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveApproveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveApproveRequest proto.InternalMessageInfo

type GetLeaveApproveResponse struct {
	Getleaverequest []*GetLeaveRequest `protobuf:"bytes,1,rep,name=Getleaverequest,proto3" json:"Getleaverequest,omitempty"`
}

func (m *GetLeaveApproveResponse) Reset()         { *m = GetLeaveApproveResponse{} }
func (m *GetLeaveApproveResponse) String() string { return proto.CompactTextString(m) }
func (*GetLeaveApproveResponse) ProtoMessage()    {}
func (*GetLeaveApproveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{8}
}
func (m *GetLeaveApproveResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveApproveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveApproveResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveApproveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveApproveResponse.Merge(m, src)
}
func (m *GetLeaveApproveResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveApproveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveApproveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveApproveResponse proto.InternalMessageInfo

func (m *GetLeaveApproveResponse) GetGetleaverequest() []*GetLeaveRequest {
	if m != nil {
		return m.Getleaverequest
	}
	return nil
}

type GetRegisterAdminRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *GetRegisterAdminRequest) Reset()         { *m = GetRegisterAdminRequest{} }
func (m *GetRegisterAdminRequest) String() string { return proto.CompactTextString(m) }
func (*GetRegisterAdminRequest) ProtoMessage()    {}
func (*GetRegisterAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{9}
}
func (m *GetRegisterAdminRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetRegisterAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetRegisterAdminRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetRegisterAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRegisterAdminRequest.Merge(m, src)
}
func (m *GetRegisterAdminRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetRegisterAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRegisterAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRegisterAdminRequest proto.InternalMessageInfo

func (m *GetRegisterAdminRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetRegisterAdminResponse struct {
	//repeated GetAdminRequest GetAdminrequest=1;
	Admin *Admin `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (m *GetRegisterAdminResponse) Reset()         { *m = GetRegisterAdminResponse{} }
func (m *GetRegisterAdminResponse) String() string { return proto.CompactTextString(m) }
func (*GetRegisterAdminResponse) ProtoMessage()    {}
func (*GetRegisterAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{10}
}
func (m *GetRegisterAdminResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetRegisterAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetRegisterAdminResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetRegisterAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRegisterAdminResponse.Merge(m, src)
}
func (m *GetRegisterAdminResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetRegisterAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRegisterAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRegisterAdminResponse proto.InternalMessageInfo

func (m *GetRegisterAdminResponse) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

func init() {
	proto.RegisterType((*GetLeaveRequest)(nil), "lms.v1beta1.GetLeaveRequest")
	proto.RegisterType((*GetstudentsRequest)(nil), "lms.v1beta1.GetstudentsRequest")
	proto.RegisterType((*GetstudentsResponse)(nil), "lms.v1beta1.GetstudentsResponse")
	proto.RegisterType((*GetstudentRequest)(nil), "lms.v1beta1.GetstudentRequest")
	proto.RegisterType((*GetstudentResponse)(nil), "lms.v1beta1.GetstudentResponse")
	proto.RegisterType((*GetLeaveReq)(nil), "lms.v1beta1.GetLeaveReq")
	proto.RegisterType((*GetLeaveRequestResponse)(nil), "lms.v1beta1.GetLeaveRequestResponse")
	proto.RegisterType((*GetLeaveApproveRequest)(nil), "lms.v1beta1.GetLeaveApproveRequest")
	proto.RegisterType((*GetLeaveApproveResponse)(nil), "lms.v1beta1.GetLeaveApproveResponse")
	proto.RegisterType((*GetRegisterAdminRequest)(nil), "lms.v1beta1.GetRegisterAdminRequest")
	proto.RegisterType((*GetRegisterAdminResponse)(nil), "lms.v1beta1.GetRegisterAdminResponse")
}

func init() { proto.RegisterFile("cosmos/lms/v1beta1/query.proto", fileDescriptor_4aaac713669af5ad) }

var fileDescriptor_4aaac713669af5ad = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xb1, 0x6f, 0xd3, 0x40,
	0x14, 0xc6, 0xe3, 0x40, 0x68, 0x79, 0x81, 0xa2, 0x1e, 0x15, 0x58, 0xa6, 0x72, 0xc3, 0x35, 0x95,
	0x02, 0x12, 0xb6, 0x5a, 0x66, 0x24, 0x8a, 0x0a, 0x59, 0x58, 0x08, 0x1b, 0x4c, 0xd7, 0xf8, 0x29,
	0xb2, 0x14, 0xfb, 0x5c, 0xdf, 0xa5, 0x6a, 0xd8, 0x60, 0xe9, 0x8a, 0xc4, 0x3f, 0xc5, 0x58, 0x89,
	0x85, 0x11, 0x25, 0xfc, 0x21, 0x28, 0xe7, 0xbb, 0x3a, 0x36, 0x76, 0xa3, 0x6c, 0xc9, 0x7b, 0xdf,
	0xbd, 0xdf, 0xe7, 0x77, 0x9f, 0x0d, 0xee, 0x90, 0x8b, 0x88, 0x0b, 0x7f, 0x1c, 0x09, 0xff, 0xfc,
	0xf0, 0x14, 0x25, 0x3b, 0xf4, 0xcf, 0x26, 0x98, 0x4e, 0xbd, 0x24, 0xe5, 0x92, 0x93, 0xf6, 0x38,
	0x12, 0x9e, 0x6e, 0x38, 0x4f, 0x2a, 0xc4, 0xf2, 0x22, 0x53, 0x3a, 0xbb, 0x23, 0xce, 0x47, 0x63,
	0xf4, 0x59, 0x12, 0xfa, 0x2c, 0x8e, 0xb9, 0x64, 0x32, 0xe4, 0xb1, 0xc8, 0xba, 0x74, 0x1b, 0x1e,
	0xf4, 0x51, 0xbe, 0x47, 0x76, 0x8e, 0x03, 0x3c, 0x9b, 0xa0, 0x90, 0x74, 0x07, 0x48, 0x1f, 0xa5,
	0x90, 0x93, 0x00, 0x63, 0x29, 0x4c, 0xf5, 0x2d, 0x3c, 0x2c, 0x54, 0x45, 0xc2, 0x63, 0x81, 0xc4,
	0x83, 0x0d, 0x5d, 0xb3, 0xad, 0xce, 0xad, 0x5e, 0xfb, 0x68, 0xc7, 0x5b, 0x72, 0xe6, 0x7d, 0xcc,
	0x7a, 0x03, 0x23, 0xa2, 0xaf, 0x60, 0x3b, 0x1f, 0xa3, 0x67, 0x93, 0x2d, 0x68, 0x86, 0x81, 0x6d,
	0x75, 0xac, 0xde, 0xdd, 0x41, 0x33, 0x0c, 0x88, 0x0d, 0x1b, 0x2c, 0x08, 0x52, 0x14, 0xc2, 0x6e,
	0xaa, 0xa2, 0xf9, 0x4b, 0x4f, 0x96, 0xbd, 0x55, 0x9b, 0xb0, 0x56, 0x9b, 0xb8, 0x0f, 0xed, 0xa5,
	0x87, 0xa6, 0x9f, 0xe1, 0x71, 0x69, 0x07, 0xd7, 0x93, 0x5f, 0xc3, 0xbd, 0xf1, 0xa2, 0x9e, 0x66,
	0x75, 0xfd, 0x8c, 0xbb, 0x85, 0xf1, 0xe5, 0xb3, 0x85, 0x13, 0xd4, 0x86, 0x47, 0x46, 0x70, 0x9c,
	0x24, 0x29, 0xcf, 0xf7, 0xcc, 0x72, 0xec, 0x75, 0x47, 0x63, 0xdf, 0xa9, 0x5b, 0x59, 0x9b, 0x5c,
	0x3e, 0x44, 0x5f, 0x28, 0xc4, 0x00, 0x47, 0xa1, 0x90, 0x98, 0x1e, 0x07, 0x51, 0x18, 0x9b, 0x9d,
	0x13, 0xb8, 0x1d, 0xb3, 0x08, 0xf5, 0xd6, 0xd5, 0x6f, 0x7a, 0x02, 0xf6, 0xff, 0x72, 0x6d, 0xa9,
	0x07, 0x2d, 0xb6, 0x28, 0xe8, 0x0d, 0x93, 0x82, 0x91, 0x4c, 0x9a, 0x09, 0x8e, 0x2e, 0x5b, 0xd0,
	0xfa, 0xb0, 0x88, 0x2a, 0xf9, 0x6a, 0xc1, 0x66, 0x1f, 0xa5, 0xea, 0x92, 0x6e, 0xd9, 0x7a, 0x95,
	0x2d, 0xe7, 0x60, 0x85, 0x2a, 0x73, 0x43, 0x7b, 0xdf, 0x7e, 0xfd, 0xfd, 0xd1, 0xa4, 0xa4, 0xe3,
	0x57, 0x44, 0x5f, 0xd9, 0xd0, 0x89, 0x21, 0x5f, 0xd4, 0x5d, 0xeb, 0x08, 0x08, 0xb2, 0x57, 0x9e,
	0x5f, 0xca, 0xb9, 0xd3, 0xa9, 0x17, 0xac, 0xcd, 0x9e, 0x02, 0xe4, 0x6c, 0xe2, 0xd6, 0x4c, 0x36,
	0xe4, 0xbd, 0xda, 0xbe, 0x06, 0x3f, 0x57, 0xe0, 0x2e, 0xa1, 0x55, 0x60, 0x2d, 0xce, 0xd1, 0x9b,
	0x26, 0x1d, 0xe4, 0xc6, 0xd0, 0x38, 0xdd, 0x1b, 0x23, 0x65, 0xd8, 0xcf, 0x14, 0x7b, 0x9f, 0x3c,
	0xad, 0x67, 0x1b, 0xf4, 0xa5, 0x05, 0x5b, 0x8b, 0x5b, 0x1f, 0x0e, 0x31, 0xd1, 0x0e, 0xf6, 0x2b,
	0x19, 0xc5, 0xf7, 0xa1, 0xc6, 0x48, 0xe9, 0xd5, 0x58, 0x67, 0x09, 0x6f, 0x0e, 0x7e, 0xce, 0x5c,
	0xeb, 0x6a, 0xe6, 0x5a, 0x7f, 0x66, 0xae, 0xf5, 0x7d, 0xee, 0x36, 0xae, 0xe6, 0x6e, 0xe3, 0xf7,
	0xdc, 0x6d, 0x7c, 0x6a, 0x5f, 0xa8, 0x73, 0x72, 0x9a, 0xa0, 0x38, 0xbd, 0xa3, 0x3e, 0x85, 0x2f,
	0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x78, 0x69, 0x98, 0x54, 0x74, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	GetAdmin(ctx context.Context, in *GetRegisterAdminRequest, opts ...grpc.CallOption) (*GetRegisterAdminResponse, error)
	// GetStudent adds new student
	GetStudents(ctx context.Context, in *GetstudentsRequest, opts ...grpc.CallOption) (*GetstudentsResponse, error)
	GetStudent(ctx context.Context, in *GetstudentRequest, opts ...grpc.CallOption) (*GetstudentResponse, error)
	// GetLeave request a new leave
	GetLeave(ctx context.Context, in *GetLeaveRequest, opts ...grpc.CallOption) (*GetLeaveRequestResponse, error)
	GetAcceptLeave(ctx context.Context, in *GetLeaveApproveRequest, opts ...grpc.CallOption) (*GetLeaveApproveResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetAdmin(ctx context.Context, in *GetRegisterAdminRequest, opts ...grpc.CallOption) (*GetRegisterAdminResponse, error) {
	out := new(GetRegisterAdminResponse)
	err := c.cc.Invoke(ctx, "/lms.v1beta1.Query/GetAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetStudents(ctx context.Context, in *GetstudentsRequest, opts ...grpc.CallOption) (*GetstudentsResponse, error) {
	out := new(GetstudentsResponse)
	err := c.cc.Invoke(ctx, "/lms.v1beta1.Query/GetStudents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetStudent(ctx context.Context, in *GetstudentRequest, opts ...grpc.CallOption) (*GetstudentResponse, error) {
	out := new(GetstudentResponse)
	err := c.cc.Invoke(ctx, "/lms.v1beta1.Query/GetStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLeave(ctx context.Context, in *GetLeaveRequest, opts ...grpc.CallOption) (*GetLeaveRequestResponse, error) {
	out := new(GetLeaveRequestResponse)
	err := c.cc.Invoke(ctx, "/lms.v1beta1.Query/GetLeave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAcceptLeave(ctx context.Context, in *GetLeaveApproveRequest, opts ...grpc.CallOption) (*GetLeaveApproveResponse, error) {
	out := new(GetLeaveApproveResponse)
	err := c.cc.Invoke(ctx, "/lms.v1beta1.Query/GetAcceptLeave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	GetAdmin(context.Context, *GetRegisterAdminRequest) (*GetRegisterAdminResponse, error)
	// GetStudent adds new student
	GetStudents(context.Context, *GetstudentsRequest) (*GetstudentsResponse, error)
	GetStudent(context.Context, *GetstudentRequest) (*GetstudentResponse, error)
	// GetLeave request a new leave
	GetLeave(context.Context, *GetLeaveRequest) (*GetLeaveRequestResponse, error)
	GetAcceptLeave(context.Context, *GetLeaveApproveRequest) (*GetLeaveApproveResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetAdmin(ctx context.Context, req *GetRegisterAdminRequest) (*GetRegisterAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdmin not implemented")
}
func (*UnimplementedQueryServer) GetStudents(ctx context.Context, req *GetstudentsRequest) (*GetstudentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudents not implemented")
}
func (*UnimplementedQueryServer) GetStudent(ctx context.Context, req *GetstudentRequest) (*GetstudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudent not implemented")
}
func (*UnimplementedQueryServer) GetLeave(ctx context.Context, req *GetLeaveRequest) (*GetLeaveRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeave not implemented")
}
func (*UnimplementedQueryServer) GetAcceptLeave(ctx context.Context, req *GetLeaveApproveRequest) (*GetLeaveApproveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAcceptLeave not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegisterAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lms.v1beta1.Query/GetAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAdmin(ctx, req.(*GetRegisterAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetstudentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lms.v1beta1.Query/GetStudents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetStudents(ctx, req.(*GetstudentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetstudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lms.v1beta1.Query/GetStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetStudent(ctx, req.(*GetstudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lms.v1beta1.Query/GetLeave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLeave(ctx, req.(*GetLeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAcceptLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaveApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAcceptLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lms.v1beta1.Query/GetAcceptLeave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAcceptLeave(ctx, req.(*GetLeaveApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lms.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdmin",
			Handler:    _Query_GetAdmin_Handler,
		},
		{
			MethodName: "GetStudents",
			Handler:    _Query_GetStudents_Handler,
		},
		{
			MethodName: "GetStudent",
			Handler:    _Query_GetStudent_Handler,
		},
		{
			MethodName: "GetLeave",
			Handler:    _Query_GetLeave_Handler,
		},
		{
			MethodName: "GetAcceptLeave",
			Handler:    _Query_GetAcceptLeave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/lms/v1beta1/query.proto",
}

func (m *GetLeaveRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetstudentsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetstudentsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetstudentsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetstudentsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetstudentsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetstudentsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Student) > 0 {
		for iNdEx := len(m.Student) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Student[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetstudentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetstudentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetstudentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetstudentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetstudentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetstudentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Student != nil {
		{
			size, err := m.Student.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetLeaveReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetLeaveRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Leaverequest) > 0 {
		for iNdEx := len(m.Leaverequest) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Leaverequest[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetLeaveApproveRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveApproveRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveApproveRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetLeaveApproveResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveApproveResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveApproveResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Getleaverequest) > 0 {
		for iNdEx := len(m.Getleaverequest) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Getleaverequest[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetRegisterAdminRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRegisterAdminRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetRegisterAdminRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetRegisterAdminResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRegisterAdminResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetRegisterAdminResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Admin != nil {
		{
			size, err := m.Admin.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetLeaveRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetstudentsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetstudentsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Student) > 0 {
		for _, e := range m.Student {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *GetstudentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetstudentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Student != nil {
		l = m.Student.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetLeaveReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetLeaveRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Leaverequest) > 0 {
		for _, e := range m.Leaverequest {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *GetLeaveApproveRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetLeaveApproveResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Getleaverequest) > 0 {
		for _, e := range m.Getleaverequest {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *GetRegisterAdminRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetRegisterAdminResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Admin != nil {
		l = m.Admin.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetLeaveRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetstudentsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetstudentsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetstudentsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetstudentsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetstudentsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetstudentsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Student", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Student = append(m.Student, &Student{})
			if err := m.Student[len(m.Student)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetstudentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetstudentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetstudentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetstudentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetstudentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetstudentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Student", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Student == nil {
				m.Student = &Student{}
			}
			if err := m.Student.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leaverequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Leaverequest = append(m.Leaverequest, &GetLeaveRequest{})
			if err := m.Leaverequest[len(m.Leaverequest)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveApproveRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveApproveRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveApproveRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveApproveResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveApproveResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveApproveResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Getleaverequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Getleaverequest = append(m.Getleaverequest, &GetLeaveRequest{})
			if err := m.Getleaverequest[len(m.Getleaverequest)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRegisterAdminRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRegisterAdminRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRegisterAdminRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRegisterAdminResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRegisterAdminResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRegisterAdminResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Admin == nil {
				m.Admin = &Admin{}
			}
			if err := m.Admin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
